version: '3.8'
services:
  database:
    container_name: database
    image: postgres:15.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=CHOOSE_A_PASSWORD
      - POSTGRES_DB=postgres
      - lc_monetary="de_DE(at)euro"
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: backend
    depends_on:
      database:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - DB_HOST=database
    ports:
      - 80:80

  frontend:
    depends_on:
      - backend
    build:
      dockerfile: Dockerfile.frontend
    ports:
      - 4200:4200
