// Generated by ts-to-zod
import { z } from 'zod';

export const userLoginInfoSchema = z.object({
  email: z.string(),
  password: z.string(),
});

export const userInfoSchema = userLoginInfoSchema.extend({
  email: z.string(),
  password: z.string(),
  firstName: z.string(),
  lastName: z.string(),
});
