// Generated by ts-to-zod
import { z } from 'zod';

export const userCredentialsSchema = z.object({
  email: z.string().email(),
  password: z.string().min(8),
});

export const userAddressSchema = z.object({
  street: z.string(),
  number: z.string(),
  city: z.string(),
  zipcode: z.string(),
});

export const userNameSchema = z.object({
  firstName: z.string(),
  lastName: z.string(),
});

export const createUserSchema = userCredentialsSchema
  .extend(userAddressSchema.shape)
  .extend(userNameSchema.shape);

export const updatePasswordSchema = z.object({
  oldPassword: z.string(),
  newPassword: z.string(),
});
