// Generated by ts-to-zod
import { z } from "zod";

export declare const userLoginInfoSchema = z.object({
  email: z.string().email(),
  password: z.string().min(8),
});

export declare const userInfoSchema = userLoginInfoSchema.extend({
  firstName: z.string(),
  lastName: z.string(),
});
